/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.sql.Date;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author max
 */
public class ComprasRealizadas extends javax.swing.JPanel {

    private DefaultTableModel tablaCompraDefault;//tabla default de los clientes
    private DefaultTableModel tablaComprasDefault;

    /**
     * Creates new form AbmClienteGui
     */
    public ComprasRealizadas() {
        initComponents();
        tablaCompraDefault = (DefaultTableModel) tablaCompra.getModel();//conveirto la tabla
        tablaComprasDefault = (DefaultTableModel) tablaCompras.getModel();
    }

    public void setActionListener(ActionListener lis) {
        this.imprimir.addActionListener(lis); //boton imprimir
        this.devolucion.addActionListener(lis); //boton devolucion
        this.modificar.addActionListener(lis); //boton modificar
        this.eliminar.addActionListener(lis); //boton eliminar
    }

     public JDateChooser getClendarioDesde(){
        return calendarioDesde;
    }
    
    public JDateChooser getClendarioHasta(){
        return calendarioHasta;
    }
    
    public JTextField getFiltroNombre() {
        return filtroNombre;
    }

    public JTextField getFiltroCuil() {
        return filtroCuil;
    }

    public JDateChooser getCalendarioCompra() {
        return calendarioCompra;
    }

    public JButton getDevolucion() {
        return devolucion;
    }

    public JButton getEliminar() {
        return eliminar;
    }

    public JButton getModificar() {
        return modificar;
    }

    public JTextField getProveedorCompra() {
        return proveedorCompra;
    }

    public JButton getImprimir() {
        return imprimir;
    }

    public DefaultTableModel getTablaCompraDefault() {
        return tablaCompraDefault;
    }

    public DefaultTableModel getTablaComprasDefault() {
        return tablaComprasDefault;
    }

    public JTextField getFiltroId() {
        return filtroId;
    }

    public JTextField getCalenDesdeText(){
        return ((JTextField)calendarioDesde.getDateEditor().getUiComponent());
    }
    
    public JTextField getCalenHastaText(){
        return ((JTextField)calendarioHasta.getDateEditor().getUiComponent());
    }
        
    public JTable getTablaCompra() {
        return tablaCompra;
    }

    public JTable getTablaCompras() {
        return tablaCompras;
    }

    public JTextField getTotalCompra() {
        return totalCompra;
    }

    public JDateChooser getCalendarioDesde() {
        return calendarioDesde;
    }

    public JDateChooser getCalendarioHasta() {
        return calendarioHasta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fondoImagen = new javax.swing.JPanel();
        panelTitulo = new org.edisoncor.gui.panel.PanelImage();
        titulo = new javax.swing.JLabel();
        panelCompra = new javax.swing.JPanel();
        labelProveedor = new javax.swing.JLabel();
        proveedorCompra = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaCompra = new javax.swing.JTable();
        labelTotal = new javax.swing.JLabel();
        totalCompra = new javax.swing.JTextField();
        labelFecha = new javax.swing.JLabel();
        calendarioCompra = new com.toedter.calendar.JDateChooser();
        panelControlFactura = new javax.swing.JPanel();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        devolucion = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        comprasRealizadas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        labelBusquedaDesde = new javax.swing.JLabel();
        labelBusquedaCuil = new javax.swing.JLabel();
        filtroCuil = new javax.swing.JTextField();
        labelBusquedaHasta = new javax.swing.JLabel();
        labelBusquedaNombre = new javax.swing.JLabel();
        filtroNombre = new javax.swing.JTextField();
        filtroId = new javax.swing.JTextField();
        labelbusquedaID = new javax.swing.JLabel();
        calendarioDesde = new com.toedter.calendar.JDateChooser();
        calendarioHasta = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(825, 448));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(822, 448));

        fondoImagen.setPreferredSize(new java.awt.Dimension(820, 400));

        panelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/fondoCliente2.jpg"))); // NOI18N
        panelTitulo.setPreferredSize(new java.awt.Dimension(329, 49));

        titulo.setFont(new java.awt.Font("Century Schoolbook L", 3, 24)); // NOI18N
        titulo.setText("COMPRAS REALIZADAS");
        panelTitulo.add(titulo);

        panelCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        labelProveedor.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelProveedor.setText("Proveedor");

        proveedorCompra.setEditable(false);

        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Articulo", "Precio", "importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tablaCompra);
        tablaCompra.getColumnModel().getColumn(0).setPreferredWidth(75);
        tablaCompra.getColumnModel().getColumn(0).setMaxWidth(75);
        tablaCompra.getColumnModel().getColumn(2).setPreferredWidth(75);
        tablaCompra.getColumnModel().getColumn(2).setMaxWidth(75);
        tablaCompra.getColumnModel().getColumn(3).setPreferredWidth(75);
        tablaCompra.getColumnModel().getColumn(3).setMaxWidth(75);

        labelTotal.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelTotal.setText("Total");

        totalCompra.setEditable(false);

        labelFecha.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelFecha.setText("Fecha");

        calendarioCompra.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout panelCompraLayout = new javax.swing.GroupLayout(panelCompra);
        panelCompra.setLayout(panelCompraLayout);
        panelCompraLayout.setHorizontalGroup(
            panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(panelCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addComponent(labelProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proveedorCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelCompraLayout.setVerticalGroup(
            panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompraLayout.createSequentialGroup()
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelProveedor)
                        .addComponent(proveedorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelFecha))
                    .addComponent(calendarioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotal)))
        );

        panelControlFactura.setLayout(new java.awt.GridLayout(1, 0));

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/modificar.png"))); // NOI18N
        modificar.setToolTipText("Modificar compra");
        panelControlFactura.add(modificar);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/borrar.png"))); // NOI18N
        eliminar.setToolTipText("Eliminar el registro de la compra de la base de datos");
        panelControlFactura.add(eliminar);

        devolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/devolver.png"))); // NOI18N
        devolucion.setToolTipText("Compra cancelada (Se borrará)");
        panelControlFactura.add(devolucion);

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/imprimir.png"))); // NOI18N
        imprimir.setToolTipText("Abrir dialogo de impresion o exportarción");
        panelControlFactura.add(imprimir);

        comprasRealizadas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compras realizadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        tablaCompras.setAutoCreateRowSorter(true);
        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Compra", "Proveedor", "fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCompras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tablaCompras);

        labelBusquedaDesde.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelBusquedaDesde.setText("Desde");

        labelBusquedaCuil.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelBusquedaCuil.setText("Cuil");

        filtroCuil.setToolTipText("filtrar facturas por nombre del cliente");

        labelBusquedaHasta.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelBusquedaHasta.setText("Hasta");

        labelBusquedaNombre.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelBusquedaNombre.setText("Nombre");

        filtroNombre.setToolTipText("Filtrar facturas por apellido del cliente");

        filtroId.setToolTipText("Filtrar facturas por ID del cliente");

        labelbusquedaID.setText("ID");

        calendarioDesde.setDateFormatString("yyyy-MM-dd");

        calendarioHasta.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout comprasRealizadasLayout = new javax.swing.GroupLayout(comprasRealizadas);
        comprasRealizadas.setLayout(comprasRealizadasLayout);
        comprasRealizadasLayout.setHorizontalGroup(
            comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprasRealizadasLayout.createSequentialGroup()
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBusquedaCuil)
                    .addComponent(labelBusquedaNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtroCuil)
                    .addComponent(filtroNombre)))
            .addGroup(comprasRealizadasLayout.createSequentialGroup()
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, comprasRealizadasLayout.createSequentialGroup()
                        .addComponent(labelBusquedaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarioHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                    .addGroup(comprasRealizadasLayout.createSequentialGroup()
                        .addComponent(labelBusquedaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(2, 2, 2)
                .addComponent(labelbusquedaID)
                .addGap(1, 1, 1)
                .addComponent(filtroId, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
        );
        comprasRealizadasLayout.setVerticalGroup(
            comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprasRealizadasLayout.createSequentialGroup()
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBusquedaCuil)
                    .addComponent(filtroCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBusquedaNombre)
                    .addComponent(filtroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBusquedaDesde)
                    .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(filtroId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelbusquedaID))
                    .addComponent(calendarioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comprasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBusquedaHasta))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoImagenLayout = new javax.swing.GroupLayout(fondoImagen);
        fondoImagen.setLayout(fondoImagenLayout);
        fondoImagenLayout.setHorizontalGroup(
            fondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comprasRealizadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelControlFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fondoImagenLayout.setVerticalGroup(
            fondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoImagenLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoImagenLayout.createSequentialGroup()
                        .addComponent(panelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelControlFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comprasRealizadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(fondoImagen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendarioCompra;
    private com.toedter.calendar.JDateChooser calendarioDesde;
    private com.toedter.calendar.JDateChooser calendarioHasta;
    private javax.swing.JPanel comprasRealizadas;
    private javax.swing.JButton devolucion;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField filtroCuil;
    private javax.swing.JTextField filtroId;
    private javax.swing.JTextField filtroNombre;
    private javax.swing.JPanel fondoImagen;
    private javax.swing.JButton imprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel labelBusquedaCuil;
    private javax.swing.JLabel labelBusquedaDesde;
    private javax.swing.JLabel labelBusquedaHasta;
    private javax.swing.JLabel labelBusquedaNombre;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelProveedor;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelbusquedaID;
    private javax.swing.JButton modificar;
    private javax.swing.JPanel panelCompra;
    private javax.swing.JPanel panelControlFactura;
    private org.edisoncor.gui.panel.PanelImage panelTitulo;
    private javax.swing.JTextField proveedorCompra;
    private javax.swing.JTable tablaCompra;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField totalCompra;
    // End of variables declaration//GEN-END:variables
}
